version: "3"

services:
  wap-frontend-dev:
    container_name: wap-frontend-dev
    build:
      dockerfile: local-development/Dockerfile
      context: ../
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ../public:/app/public:rw
      - ../src:/app/src:rw
