version: "3"

services:
  callforcode-wap-frontend-service:
    container_name: callforcode-wap-frontend-service
    image: wap-frontend
    build:
      dockerfile: ./local-development/Dockerfile
      context: ../../frontend/
    ports:
      - "3000:3000"
    environment:
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
    restart: always

  callforcode-wap-backend-service:
    container_name: callforcode-wap-backend-service
    image: wap-backend
    build:
      dockerfile: Dockerfile
      context: ../../backend/
    ports:
      - "5000:5000"
    environment:
      - SERVICE_BASE_URL=$SERVICE_BASE_URL
      - SERVICE_SUFFIX=/v3/translate?version=2018-05-01
      - API_ID=apikey
      - API_KEY=$API_KEY
    restart: always
